package LearningPathLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptorImpl;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptLearner = createDescriptorForLearner();
  /*package*/ final ConceptDescriptor myConceptLearningMaterial = createDescriptorForLearningMaterial();
  /*package*/ final ConceptDescriptor myConceptLesson = createDescriptorForLesson();
  /*package*/ final ConceptDescriptor myConceptMaterialType = createDescriptorForMaterialType();
  /*package*/ final ConceptDescriptor myConceptPractical = createDescriptorForPractical();
  /*package*/ final ConceptDescriptor myConceptProgressAssessment = createDescriptorForProgressAssessment();
  /*package*/ final ConceptDescriptor myConceptQuestion = createDescriptorForQuestion();
  /*package*/ final ConceptDescriptor myConceptSubTopic = createDescriptorForSubTopic();
  /*package*/ final ConceptDescriptor myConceptTheoretical = createDescriptorForTheoretical();
  /*package*/ final ConceptDescriptor myConceptTopic = createDescriptorForTopic();
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeEmail = new ConstrainedStringDatatypeDescriptorImpl(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a3fc1b9L, "Email", "r:81c1a569-f149-41bf-8e67-9dfdd0922ba5(LearningPathLanguage.structure)/5300008992263619001", "^\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*$");
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptLearner, myConceptLearningMaterial, myConceptLesson, myConceptMaterialType, myConceptPractical, myConceptProgressAssessment, myConceptQuestion, myConceptSubTopic, myConceptTheoretical, myConceptTopic);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Learner:
        return myConceptLearner;
      case LanguageConceptSwitch.LearningMaterial:
        return myConceptLearningMaterial;
      case LanguageConceptSwitch.Lesson:
        return myConceptLesson;
      case LanguageConceptSwitch.MaterialType:
        return myConceptMaterialType;
      case LanguageConceptSwitch.Practical:
        return myConceptPractical;
      case LanguageConceptSwitch.ProgressAssessment:
        return myConceptProgressAssessment;
      case LanguageConceptSwitch.Question:
        return myConceptQuestion;
      case LanguageConceptSwitch.SubTopic:
        return myConceptSubTopic;
      case LanguageConceptSwitch.Theoretical:
        return myConceptTheoretical;
      case LanguageConceptSwitch.Topic:
        return myConceptTopic;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myCSDatatypeEmail);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForLearner() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LearningPathLanguage", "Learner", 0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17a4a4L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:81c1a569-f149-41bf-8e67-9dfdd0922ba5(LearningPathLanguage.structure)/5300008992260990116");
    b.version(3);
    b.property("id", 0x498d6a190a17f9e9L).type(PrimitiveTypeId.INTEGER).origin("5300008992261011945").done();
    b.property("firstName", 0x498d6a190a17f9ebL).type(PrimitiveTypeId.STRING).origin("5300008992261011947").done();
    b.property("lastName", 0x498d6a190a17f9efL).type(PrimitiveTypeId.STRING).origin("5300008992261011951").done();
    b.property("email", 0x498d6a190a17f9f3L).type(MetaIdFactory.dataTypeId(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a3fc1b9L)).origin("5300008992261011955").done();
    b.property("fullName", 0x498d6a190a257c81L).type(PrimitiveTypeId.STRING).origin("5300008992261897345").done();
    b.aggregate("topic", 0x498d6a190a17fa04L).target(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9ceL).optional(true).ordered(true).multiple(false).origin("5300008992261011972").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLearningMaterial() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LearningPathLanguage", "LearningMaterial", 0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9d6L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:81c1a569-f149-41bf-8e67-9dfdd0922ba5(LearningPathLanguage.structure)/5300008992261011926");
    b.version(3);
    b.property("id", 0x498d6a190a183d69L).type(PrimitiveTypeId.INTEGER).origin("5300008992261029225").done();
    b.property("title", 0x498d6a190a183d6bL).type(PrimitiveTypeId.STRING).origin("5300008992261029227").done();
    b.aggregate("materialType", 0x498d6a190a183d70L).target(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9d9L).optional(false).ordered(true).multiple(false).origin("5300008992261029232").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLesson() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LearningPathLanguage", "Lesson", 0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9d3L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:81c1a569-f149-41bf-8e67-9dfdd0922ba5(LearningPathLanguage.structure)/5300008992261011923");
    b.version(3);
    b.property("id", 0x498d6a190a183d5aL).type(PrimitiveTypeId.INTEGER).origin("5300008992261029210").done();
    b.property("title", 0x498d6a190a183d5cL).type(PrimitiveTypeId.STRING).origin("5300008992261029212").done();
    b.property("description", 0x498d6a190a183d60L).type(PrimitiveTypeId.STRING).origin("5300008992261029216").done();
    b.aggregate("learningMaterials", 0x498d6a190a183d66L).target(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9d6L).optional(false).ordered(true).multiple(true).origin("5300008992261029222").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMaterialType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LearningPathLanguage", "MaterialType", 0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9d9L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:81c1a569-f149-41bf-8e67-9dfdd0922ba5(LearningPathLanguage.structure)/5300008992261011929");
    b.version(3);
    b.property("typeOfMaterial", 0x498d6a190a183d73L).type(PrimitiveTypeId.STRING).origin("5300008992261029235").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPractical() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LearningPathLanguage", "Practical", 0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9e3L);
    b.class_(false, false, false);
    // extends: LearningPathLanguage.structure.ProgressAssessment
    b.super_(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9dcL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:81c1a569-f149-41bf-8e67-9dfdd0922ba5(LearningPathLanguage.structure)/5300008992261011939");
    b.version(3);
    b.property("performanceType", 0x498d6a190a183d4fL).type(PrimitiveTypeId.STRING).origin("5300008992261029199").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProgressAssessment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LearningPathLanguage", "ProgressAssessment", 0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9dcL);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:81c1a569-f149-41bf-8e67-9dfdd0922ba5(LearningPathLanguage.structure)/5300008992261011932");
    b.version(3);
    b.property("id", 0x498d6a190a183d3dL).type(PrimitiveTypeId.INTEGER).origin("5300008992261029181").done();
    b.property("description", 0x498d6a190a183d3fL).type(PrimitiveTypeId.STRING).origin("5300008992261029183").done();
    b.alias("assessment");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQuestion() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LearningPathLanguage", "Question", 0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9e6L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:81c1a569-f149-41bf-8e67-9dfdd0922ba5(LearningPathLanguage.structure)/5300008992261011942");
    b.version(3);
    b.property("description", 0x498d6a190a183d53L).type(PrimitiveTypeId.STRING).origin("5300008992261029203").done();
    b.property("answer", 0x498d6a190a183d55L).type(PrimitiveTypeId.STRING).origin("5300008992261029205").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSubTopic() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LearningPathLanguage", "SubTopic", 0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9d1L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:81c1a569-f149-41bf-8e67-9dfdd0922ba5(LearningPathLanguage.structure)/5300008992261011921");
    b.version(3);
    b.property("id", 0x498d6a190a183d25L).type(PrimitiveTypeId.INTEGER).origin("5300008992261029157").done();
    b.property("title", 0x498d6a190a183d27L).type(PrimitiveTypeId.STRING).origin("5300008992261029159").done();
    b.property("description", 0x498d6a190a183d2bL).type(PrimitiveTypeId.STRING).origin("5300008992261029163").done();
    b.property("level", 0x498d6a190a183d32L).type(PrimitiveTypeId.STRING).origin("5300008992261029170").done();
    b.associate("parent", 0x498d6a190a17fe3dL).target(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9ceL).optional(false).origin("5300008992261013053").done();
    b.aggregate("assessment", 0x498d6a190a183d39L).target(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9dcL).optional(true).ordered(true).multiple(false).origin("5300008992261029177").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTheoretical() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LearningPathLanguage", "Theoretical", 0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9dfL);
    b.class_(false, false, false);
    // extends: LearningPathLanguage.structure.ProgressAssessment
    b.super_(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9dcL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:81c1a569-f149-41bf-8e67-9dfdd0922ba5(LearningPathLanguage.structure)/5300008992261011935");
    b.version(3);
    b.aggregate("questions", 0x498d6a190a183d48L).target(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9e6L).optional(false).ordered(true).multiple(true).origin("5300008992261029192").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTopic() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("LearningPathLanguage", "Topic", 0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9ceL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:81c1a569-f149-41bf-8e67-9dfdd0922ba5(LearningPathLanguage.structure)/5300008992261011918");
    b.version(3);
    b.property("id", 0x498d6a190a17fa0fL).type(PrimitiveTypeId.INTEGER).origin("5300008992261011983").done();
    b.property("title", 0x498d6a190a17fa11L).type(PrimitiveTypeId.STRING).origin("5300008992261011985").done();
    b.property("description", 0x498d6a190a17fa15L).type(PrimitiveTypeId.STRING).origin("5300008992261011989").done();
    b.aggregate("subtopics", 0x498d6a190a17fa1cL).target(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9d1L).optional(true).ordered(true).multiple(true).origin("5300008992261011996").done();
    return b.create();
  }
}
