package LearningPathLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Learner_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Practical_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new SubTopic_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Theoretical_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Topic_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new SubTopic_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17a4a4L), MetaIdFactory.conceptId(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9e3L), MetaIdFactory.conceptId(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9d1L), MetaIdFactory.conceptId(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9dfL), MetaIdFactory.conceptId(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9ceL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xb4e5f58b43bb499fL, 0x944fd5c2d76ce052L, 0x498d6a190a17f9d1L)).seal();
}
